# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdd08a3f53b788c5781080a55df3fd975b2995a6d5d84872c6beaf89e56a7bcbd1a850a9c22477c0f82467e3d9586c047505fcc5d8f67d86066636f21a8dc21b

test:
  secret_key_base: 0441b5691c2387b21c52b2ba19e2f2b1ab6774147425d7432e591acd37596f258981293aee6321098dbe5d988e2597851974d2215234a1c7e0c8149de3917b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
